name: Deploy to Byethost via FTP

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build assets
        run: |
          composer install --no-dev --optimize-autoloader
          npm ci
          npm run build

      - name: Deploy to Byethost via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build
          server-dir: ${{ secrets.FTP_REMOTE_PATH }}
          exclude: |
            .env
            .git/*
            .github/*
            node_modules/
            storage/*
            tests/

